# This is a basic workflow to help you get started with Actions

name: buildUpload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  #  pull_request:
  #    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checkout Code
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11


  generateApk:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      #Checkout Code
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
        #Gradle Executable
      - name: Gradle Executable
        run: chmod +x gradlew

      - name : clean gradle
        run : ./gradlew clean

      - name : Run the lane
        run :  fastlane distribute



